#encoding: utf-8
facts = ["...that the largest interesting pattern constructed, the [[caterpillar]], contains over 11 million [[cell]]s?",
"...that the [[Gosper glider gun]] was the first pattern to be discovered that exhibits infinite growth?",
"...that the [[block-laying switch engine]] and the [[glider-producing switch engine]] (and [http://conwaylife.com/forums/viewtopic.php?f=2&t=1452&p=25314#p25283 various combinations of two switch engines]) are the only infinitely-growing patterns that are known to have ever occurred naturally from an asymmetric random starting configuration?",
"...that [[oscillator]]s are known that oscillate at all [[period]]s other than 19, 23, 34, 38 and 41?",
"...that the [[pentadecathlon]] and the [[blinker]] are the only known [[oscillator]]s that are [[polyomino]]s in more than one [[phase]]?",
"...that it is impossible for a [[period]] [[:Category:Oscillators with period 3|3]] [[oscillator]] to be a [[phoenix]]?",
"...that the [[methuselah]] with the longest known lifespan, [[List of long-lived methuselahs|40514M]], lasts for over 40,000 generations before stabilizing?  The second-place holder, [[Fred]], runs for over 35,000 ticks.",
"...that [[replicator]]s with quadratic population growth are known to exist in [[Conway's Game of Life]], but none have yet been found?",
"...that the [[124P37|first]] [[112P51|known]] period 37 and 51 oscillators were found in [[:Category:Patterns found in 2009|2009]]?",
"...that a pattern whose population grows without bound but does not tend to infinity is known as a [[sawtooth]]?",
"...that there are over 6.5 million distinct [[still life#Strict still lifes|strict still life]]s with 24 or fewer [[cell]]s?",
"...that [[block-laying switch engine|some]] [[glider-producing switch engine|infinitely-growing]] patterns can be [[glider synthesis|constructed]] with as few as three [[glider]]s?",
"...that quadratically-growing patterns have been found with as few as [[switch engine ping-pong|23 initial cells]]?",
"...that the [[blinker]] is the only known [[oscillator]] that is [[one cell thick pattern|one cell thick]]?",
"...that the first [[spaceship]] found in [[Conway's Game of Life]] that travels in an [[knightship|oblique direction]] was discovered in [[:Category:patterns found in 2010|2010]]?",
"...that there are [[still life]]s that can be split into four stable [[island]]s, but not two or three?",
"...that no new [[spaceship]]s were discovered after [[:Category:Patterns found in 1970|1970]] until [[:Category:Patterns found in 1989|1989]]?",
"...that the first stable reflector was found in October 1996, and the [[Snark|first fast stable reflector]] appeared in 2013, allowing the construction of oscillators of all periods &ge;43 ticks?",
"...that twenty-two [[spaceship]] velocities have been constructed, including four infinitely adjustable families of ships?",
"...that there are 71 distinct ways for two [[glider]]s to [[glider synthesis|collide]], but it is unknown how many distinct 3-glider collisions there are?",
"...that to display the smallest known gun pattern for a [[Gemini]] spaceship at 1 cell = 1 pixel, on a standard-density video monitor, a screen over one mile square would be needed?",
"...that no odd-period glider guns were known before 1995, when a period 565 p5-spark-assisted [[B-heptomino]] loop was constructed by [[David Buckingham]]?",
"...that even though the speed limit for spaceships is c/2 in a vacuum, in a medium of [[Zebra stripes|stripes agar]] there are \"spaceships\" that can travel at lightspeed along the stripes, or two thirds of lightspeed perpendicular to the stripes?",
"...that the smallest known [[spacefiller]] pattern consists of 187 cells?",
"...that the smallest known [[sawtooth]] pattern in Conway's Life consists of only 177 ON cells?",
"...that there are now over a hundred and twenty known [[Herschel conduit|Herschel conduits]], counting stable conduits only, and a much larger number if oscillator-supported conduits are included?",
"...that [[Types_of_spaceships#Self-constructing_spaceship|Demonoids]], [[caterloopillar]]s, [[orthogonoid]]s and [[Parallel HBK|half-bakery knightships]] are the only known types of spaceships with fixed slope but adjustable speed?",
"...that a pattern exists in which no cell in the unbounded Life plane [[total aperiodic|ever becomes periodic]]?",
"...that several candidate [[universal constructor|universal constructors]] have been demonstrated in Conway’s Life, but as of June 2015 none have been formally proven to be universal?",
"...that there are dozens of known [[Cordership]] variants, including [[puffer]]s, [[rake]]s and [[wickstretcher]]s, with periods of any multiple of 96?",
"...that [[greyship]]s have been constructed with speeds of c/2, c/3, c/4, c/5 and 2c/5?",
"...that most [[greyship]]s travel parallel to the stripes in their included agars, but a few travel perpendicular to the stripes, or \"against the grain\"?",
"...that a pattern has been constructed that calculates and prints out the digits of pi in decimal, and a similar one prints out the decimal digits of the Golden Ratio?",
"...that several different patterns have been constructed to calculate and display the sequence of prime numbers, and some have been adapted to display only prime pairs or Fermat primes?",
"...that two completely different types of knightships, the [[waterbear]] and the [[half-baked knightship]], were constructed in 2014?",
"...that no Caterpillar-type spaceships were completed for almost ten years after the original [[Caterpillar]] was constructed in 2004, but that two different designs, the [[waterbear]] and the [[centipede]], were finished in 2014?",
"...that the first spiral-growth pattern in Conway's Life was constructed in 2014?",
"...that among known glider recipes for irreducible objects, the [[Gemini|Gemini spaceship]] has the largest known minimal recipe, currently 173,449 gliders &mdash; the runner-up being the [[Parallel HBK]] with a 38,380-glider synthesis?",
"...that it was shown in 2014 that any salvo of gliders, no matter how tightly packed, can be constructed by crashing together gliders whose initial positions are farther apart than any chosen finite distance?",
"...that no spaceships with velocities other than c/4 diagonal (glider), c/2 orthogonal (*WSS variants), and c/12 diagonal (Corderships) had known glider syntheses until 2003, when a 2c/5 spaceship gun was constructed?",
"...that after ten years with no new small spaceship syntheses, a glider construction was found for the c/7 [[loafer]] in 2013?",
"...that glider constructions for three previously inconstructible spaceships (the [[dart]], the [[crab]], and the [[Parallel HBK]]) were discovered in 2014?",
"...that glider constructions for the [[B29]], [[X66]], [[X66#Image_gallery|half-X66 with HWSS]], [[Pushalong 1]], [[25P3H1V0.1]], [[30P5H2V0]], [[30P4H2V0.4]], a [[pufferfish]] spaceship, and the [[weekender]] were discovered in 2015 &mdash; after fifteen years of intermittent efforts in the case of the weekender?",
"...that since 2014, more new spaceship syntheses have been completed than were found in all the years between 1970 and 2013?",
"...that as of 15 August 2017 there are [http://www.conwaylife.com/forums/viewtopic.php?f=2&t=1394&p=48924#p48924 223 different still lifes] known to be constructible by colliding four gliders, but it is likely that this list is not complete?",
"...that in 2014 a [[Pufferfish|new natural infinite growth pattern]] was discovered, starting from a symmetric random starting configuration?",
"...that the [[Gemini|first self-constructing Conway's Life pattern]] was built in 2010?",
"...that the first glider synthesis for a [[25P3H1V0.2|c/3 spaceship]] was [http://conwaylife.com/forums/viewtopic.php?f=2&t=1557&p=16241#p16241 completed] in 2014?",
"...that the first \"macro-spaceship\" gun (a [[Gemini]] spaceship gun) was constructed in 2010, followed by the [[HBK gun]] in January 2015 and a [[Demonoid]] gun in December 2015?",
"...that the [[waterbear]] is the single known high-speed oblique spaceship, many orders of magnitude faster than [[Gemini]] spaceships and [[half-baked knightship]]s?",
"...that there are no known direct reflectors for [[lightspeed wire]] signals, or for signals in 2c/3 wires, but that very large reflectors for these signals can be constructed using stable or periodic circuitry?",
"...that 24 ten-cell patterns exhibit infinite growth, with 17 unique pattern types, but that it has been proven that no nine-cell pattern exhibits infinite growth?",
"...that all still lifes up to 18 bits have a known [[glider synthesis]], but it is still not known whether all still lifes are synthesizable?",
"...that the [[French kiss]] remained without a glider synthesis until 2013?",
"...that Adam P. Goucher's distributed [[Catagolue]] soup-search project, started in February 2015, has already tested more random [[soup]]s than any previous such project, and has contributed to the reduction of many [[glider synthesis|glider construction]] recipes?",
"...that any glider-constructible Life pattern can be constructed with a fixed maximum number of gliders N, probably less than 1000?  It is only necessary to construct a sliding-block decoder, which self-destructs after converting the position of a far-distant block into a slow-salvo recipe that constructs the required pattern.",
"...that [[Copperhead]] is not only the first [[c/10 orthogonal]] [[spaceship]] ever found, but also remarkably compact for a pattern not discovered until 2016?",
"...that [[loafer]] is the fifth smallest non-flotilla spaceship, but was discovered 43 years after the four spaceships smaller than it?",
"...that despite being the fourth smallest non-flotilla orthogonal spaceship, [[loafer]] has never appeared from a single randomly generated [[soup]]?",
"...that all known glider eaters take at least four ticks to recover to their original state after eating a glider?",
"...that [[Centipede caterloopillar|the smallest]] [[31c/240 orthogonal|31c/240 spaceship]] does not make use of the [[31c/240 reaction]]?",
"...that there is roughly one chance in 10^(N/3) that a still life appearing out of random soup will have a population of exactly N cells?",
"...that the number of still lifes with N+1 bits is roughly 2.48 times larger than the number of N-bit still lifes?",
"...that the odds of a randomly-chosen 20x20 soup pattern being a [[methuselah]] that lasts between 1000N and 1000(N+1) ticks, is roughly the same as the odds that it will last '''any''' amount of time longer than 1000x(N+1) ticks?",
"...that all [[still life]]s up to [[:Category:Strict still lifes with 16 cells|16 cells]] can be [[glider synthesis|synthesized]] at a cost of less than one [[glider]] per cell?",
"...that absolutely no [[Spaceship#Elementary_spaceships|elementary]] [[knightship]]s have been discovered as of 2016, though there has been at least one [[Almost knightship|very close call]]?",
"...that there is a 6x2 counterexample to the [[Coolout Conjecture]], proving that patterns that are internally compatible with stability can not always be made part of a larger still life, no matter what cells are added around the edges?",
"...that a Conway's Life pattern representing a complete [http://conwaylife.com/forums/viewtopic.php?f=2&t=2561 programmable 8-bit computer], consisting only of [[buckaroo]]s, p60 glider guns, and glider duplicators, was completed in November 2016?",
"...that whilst no very small [[knightship]]s have been found at all in B3/S23, at least two naturally occurring reactions have been discovered in [[Pedestrian Life|B38/S23]] that travel in an oblique direction?",
"...that not all [[:Category:Oscillators with volatility 1.00|1.00 volatility oscillators]] are [[phoenix]]es?",
"...that no pattern inside a 6x6 bounding box is a [[Garden of Eden]]?",
"...that [[Garden of Eden]] patterns with only 45 ON cells have been found?",
"...that it is known that no [[Garden of Eden]] patterns exist that are 1, 2, or 3 cells high, but that it is currently an open question whether a 4-cell-high GoE can be constructed?",
"...that 6-cell-high [[Garden of Eden]] patterns were constructed as far back as 1973, but 5-cell-high GoEs were unknown until Steven Eker found some in 2016?",
"...that in 2016, [[Grandfather problem|patterns were found]] that have great-great-grandparents but no great-great-great-grandparents?",
"...that no way is known for a 3x3 pattern to be tiled into an MxN rectangle to produce a [[Garden of Eden]], but that there are 4x3, 4x4 and larger tiles that can be repeated in this way to produce GoEs?",
"...that there are spaceship stabilizations of agars?",
"...that [[block]] is the only known finite [[still life]] where each cell has exactly 3 neighbours?",
"...that all [[strict still life]]s up to and including 13 cells, and all but two with 14 cells, have been found via soup searching using [[apgsearch]]?",
"...that [[c/2 orthogonal]] and [[c/4 diagonal]] are the only speeds of spaceships seen to emerge from asymmetric soups on [[Catagolue]]?",
"...that all currently known standard Herschel conduits produce the same Herschel great-grandfather pattern, except for [[Fx158]]?",
"...that [[eater 1]] is the smallest asymmetric [[still life]]?",
"...that in [[Conway's Game of Life|Life]], no [[spaceship]] can exist with a speed of (m,n)[[speed of light|c]]/x where (m+n)/x > 0.5?",
"...that an N-bit [[strict still life]] &ndash; specifically, some length of long long (...) [[boat]] or [[barge]] &ndash; can be constructed for any odd integer N using no more than 39 gliders, and for any even integer N using no more than 38 gliders, using a temporary [[tubstretcher]]?",
"...that an N-bit period-2 [[oscillator]] can be constructed for any odd integer N using no more than 45 gliders, and for any even integer N using no more than 46 gliders, using a temporary [[tubstretcher]]?",
"...that it is [[Unique father problem|currently an open question]] as to if there exists a periodic pattern whose only predecessors are its own evolutionary sequence?",
"...that it can be proved [[reflectorless rotating oscillator]]s exist in Life, although none have yet been found or constructed?",
"...that there are currently known elementary spaceships with speeds [[c/7 orthogonal|c/7]] and [[c/10 orthogonal]], but none with [[c/8 orthogonal|c/8]] or [[c/9 orthogonal|c/9]]?",
"...that there are currently known elementary spaceships with speeds [[c/7 diagonal|c/7]] and [[c/12 diagonal]], but none with c/8, c/9, c/10 or c/11?",
"...that while the speed limit for orthogonal spaceships in rules using the [[Moore neighbourhood]] is [[c orthogonal]], spaceships in [[Larger than Life]] rules are capable of breaking this barrier?",
"...that without the use of [[adjustable glider loops]], there are no known oscillators with periods [[:Category:Oscillators with period 43|43]], [[:Category:Oscillators with period 49|49]] or [[:Category:Oscillators with period 53|53]]?",
"...that without the use of [[Herschel loops]] or [[adjustable glider loops]], there are no known oscillators with periods [[:Category:Oscillators with period 57|57]], [[:Category:Oscillators with period 59|59]] or [[:Category:Oscillators with period 61|61]]?"]
